### ISSUE TITLE
Currently the execution is cluttered with (too) many options

### ISSUE THREAD

**Issue by samueloettl** [samueloettl/ethzVideoDL#2]
### Possible Solution:

Add command line arguments and only use the current mode when no arguments are given.
Maybe a -i for interactive (current) mode.

But then add a --url argument that when supplied just downloads from there with default settings and without much questions.

Maybe also add a argument for folder path and so on...

**Comment by tiaguinho-code** [comment]
Added fundamental argument flags with commit 94ff72573d22e87b113e5cd7c2ffef061e06d0e6

**Comment by tiaguinho-code** [comment]
Added fundamental argument flags with commit https://github.com/samueloettl/ethzVideoDL/commit/94ff72573d22e87b113e5cd7c2ffef061e06d0e6
